-- 工位类型
INSERT INTO `ry-vue`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (100, '工位类型', 'station_type', '0', 'admin', '2024-02-29 14:11:28', '', NULL, NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (100, 0, '人工工位', '0', 'station_type', '', 'default', 'N', '0', 'admin', '2024-02-29 14:12:03', 'admin', '2024-02-29 14:16:10', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (101, 1, '自动工位', '1', 'station_type', NULL, 'default', 'N', '0', 'admin', '2024-02-29 14:12:23', '', NULL, NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (102, 2, '半自动工位', '2', 'station_type', NULL, 'default', 'N', '0', 'admin', '2024-02-29 14:12:41', 'admin', '2024-02-29 14:13:09', NULL);

--设备状态
INSERT INTO `ry-vue`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (101, '设备状态', 'equip_status', '0', 'admin', '2024-03-01 13:27:09', '', NULL, NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (103, 0, '运行', '0', 'equip_status', NULL, 'success', 'Y', '0', 'admin', '2024-03-01 13:34:16', 'admin', '2024-03-01 17:06:38', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (104, 1, '停止', '1', 'equip_status', NULL, 'warning', 'N', '0', 'admin', '2024-03-01 13:34:47', 'admin', '2024-03-01 17:06:48', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (105, 2, '故障', '2', 'equip_status', NULL, 'danger', 'N', '0', 'admin', '2024-03-01 13:35:06', 'admin', '2024-03-01 17:06:53', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (106, 3, '维修中', '3', 'equip_status', NULL, 'danger', 'N', '0', 'admin', '2024-03-01 13:36:37', 'admin', '2024-03-01 17:07:06', NULL);

--设备分类
INSERT INTO `ry-vue`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (102, '设备分类', 'equip_classif', '0', 'admin', '2024-03-01 13:27:39', 'admin', '2024-03-01 13:51:02', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (107, 0, 'A类', '0', 'equip_classif', NULL, 'primary', 'Y', '0', 'admin', '2024-03-01 13:47:14', 'admin', '2024-03-01 17:06:09', NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (108, 1, 'B类', '1', 'equip_classif', NULL, 'default', 'N', '0', 'admin', '2024-03-01 13:51:31', '', NULL, NULL);
INSERT INTO `ry-vue`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (109, 2, 'C类', '2', 'equip_classif', NULL, 'default', 'N', '0', 'admin', '2024-03-01 13:52:22', 'admin', '2024-03-01 13:52:33', NULL);
